### PR TITLE
Search function

### PR DESCRIPTION
**Pull request by ismail-ahmed0149**
This branch implements search functionality across all articles that the user is subscribed to. In order to get more accurate searches, I used a fuzzy string searching library called fuzzywuzzy (originally implemented in Python, but using a Java port). I didn't get a chance to implement filtering due to time constraints.

https://github.com/xdrop/fuzzywuzzy

### CODE REVIEW

**Review by Benson-chou — APPROVED** [review]
Looks good! made MainActivity cleaner without breaking clean architecture. search function working as intended too.

**Review by taizhng — APPROVED** [review]
Looks great!

Fuzzy search working as intended.

I really liked how you refactored the Card stuff from ComponentActivity into a separate card class. Really well done to follow clean architecture.

**Comment by hisbaan** [comment]
> I really liked how you refactored the Card stuff from ComponentActivity into a separate card class. Really well done to follow clean architecture.
 
If you look at the git history, it's actually gone in and out of MainActivity quite a few times... 😅

**Comment by taizhng** [comment]
> If you look at the git history, it's actually gone in and out of MainActivity quite a few times... 😅

Trust the process 👀

**Pull request merged**
