### PR TITLE
Add dynamic open-source license information

### PR DESCRIPTION
**Pull request by hisbaan**
This branch adds dynamic open-source license information. It is accessible via `Settings > Open-Source Licenses`. The list is generated upon compile time by a grade plugin as a JSON file, which is then used to render the list in the application.

https://user-images.githubusercontent.com/34548959/143969911-3a10a991-6ea2-4cf5-a3cc-0bfbbba35c5c.mp4

### CODE REVIEW

**Review by Benson-chou — APPROVED** [review]
Looks good and clean!

**Review by Just-Call-Sal — COMMENTED** [review]
Good overall code organization and documentation! I noticed that in build.gradle you changed "kotlinCompilerVersion" from 1.5.31 to 1.5.21, how come?

**Comment by hisbaan** [comment]
> Good overall code organization and documentation! I noticed that in build.gradle you changed "kotlinCompilerVersion" from 1.5.31 to 1.5.21, how come?

I'm not sure, I'll remedy that

**Review by Just-Call-Sal — APPROVED** [review]
Alright! Looks good to me then 👍

**Pull request merged**
