### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by hisbaan**
This branch adds a settings activity. The main settings here are the theme and cache timings, but the provided composables allow for easy expansion in the future. This also implements the theming and cache timings in all the other activities. The settings also provide lots of information settings such as the open-source libraries used, links to the source code, releases, etc. There are some things not filled in with TODOs left in their place but this is intentional. We do not yet have all the information required to complete these items.

### CODE REVIEW

**Review by ismail-ahmed0149 — APPROVED** [review]
Everything looks good and well-documented. I also like how you made more general Composables to make expansion of this feature easier in the future. The demo also looked very nice.

**Review by eamonma — APPROVED** [review]
A little long, potentially can modularize SettingsActivity in the future. Good comments and documentation.

**Review by Just-Call-Sal — APPROVED** [review]
This branch adds quite a lot to the program, I really like the documentation in SettingsActivity.

**Comment by hisbaan** [comment]
> A little long, potentially can modularize SettingsActivity in the future. Good comments and documentation.

We could probably extract all of the composables into their own classes. Would require some context parameters to be passed to them for some of their actions but other than that, it would be pretty painless.

**Pull request merged**
