### PR TITLE
Bookmarking

### PR DESCRIPTION
**Pull request by ismail-ahmed0149**
This branch implements a bookmarks page where you can view articles that you have bookmarked. The way that it works currently is that when you toggle the flag icon to remove a bookmark, your changes won't be saved to the database unless you go back to the main menu and then back to the bookmarks page.  Here's a picture of how each article would look, sorry for the pixelation.

image

### CODE REVIEW

**Review by hisbaan — APPROVED** [review]
Looks good to me, we could probably add updating the database right away as soon as the user clicks the button, however, that may not actually be necessary because onPause/onStop will always be called, regardless of how the user exits the activity (whether that be going back to the previous activity or exiting the app then and there) so the changes should persist. I'll go ahead and fix the merge conflicts then we should be good to merge.

**Comment by hisbaan** [comment]
Alright, the merge conflicts should be gone now, so we'll get one more person to review and then we can go ahead and merge it. Good work!

**Review by eamonma — APPROVED** [review]
Looks good, though we could name the parameter to be more explicit when we construct an Article, specifically naming the bookmarked parameter on line 139 in PullFeed.

**Comment by hisbaan** [comment]
> Looks good, though we could name the parameter to be more explicit when we construct an Article, specifically naming the bookmarked parameter on line 139 in PullFeed.

What do you suggest? Something like isBookmarked to indicate that it's a boolean? Also it being perpetually true is just a temporary thing for testing I think - we will probably change that to false and then persist older articles or if an article is repeated, keep the traits of the old one but the user-set information from the new one.

**Pull request merged**
