### PR TITLE
Mainpage

### PR DESCRIPTION
**Pull request by Macdeini**
Finished the functionality and display of the main UI page

### CODE REVIEW

**Comment by hisbaan** [comment]
The actual code looks good, but I think that some things need to be restructured so that we can have this work well with other components of the app.

**Review by simonchenwastaken — APPROVED** [review]
Approve pull

**Comment by Macdeini** [comment]
Nice job. Good work as always Eamon.

**Comment by taizhng** [comment]
This PR branch got a little out of hand.

The code, however is excellent work Minions.

**Review by Just-Call-Sal — APPROVED** [review]
Great job

**Pull request merged**
