### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by eamonma**

### CODE REVIEW

**Review by is-ahmed — APPROVED** [review]
LGTM!!!!1!

**Review by taizhng — APPROVED** [review]
LFG!!

**Review by hisbaan — APPROVED** [review]
Very pog change

**Comment by Benson-chou** [comment]
LGTM

**Review by Benson-chou — APPROVED** [review]
LG

**Review by chen-simon — APPROVED** [review]
lgtm!!! 👍 🚀

**Review by Macdeini — APPROVED** [review]
Inshallah

**Review by Just-Call-Sal — APPROVED** [review]
Most halal PR, LGTM 👍

**Pull request merged**
