### PR TITLE
Add boundary between UI and Operation

### PR DESCRIPTION
**Pull request by Just-Call-Sal**
Added a boundary between UI classes and FetchFeed in order to reduce coupling between these classes.

### CODE REVIEW

**Comment by hisbaan** [comment]
Looks good! Good job reducing coupling!

**Review by hisbaan — APPROVED** [review]
Looks good! Good job reducing coupling!

**Review by Macdeini — APPROVED** [review]
Good work, but I think we should rename either PullFeed or FetchFeed to highlight their differences.

**Comment by hisbaan** [comment]
> Good work, but I think we should rename either PullFeed or FetchFeed to highlight their differences.

I agree. I think that would be very good. Maybe we rename pull feed to viewModel? Since that's what it's kind of like in clean architecture terms.

**Comment by Just-Call-Sal** [comment]
> > Good work, but I think we should rename either PullFeed or FetchFeed to highlight their differences.
> 
> I agree. I think that would be very good. Maybe we rename pull feed to viewModel? Since that's what it's kind of like in clean architecture terms.

Okay, will do!

**Pull request merged**
